In [1]:
import math

In [6]:
import numpy

##### array

In [25]:
import numpy as np
array1 = np.array([1,2,3])
array2 = np.array([[1,2,3], 
                   [4,5,6]])
array1

array([1, 2, 3])

In [21]:
[1,2,3] * [4,5,6]

TypeError: can't multiply sequence by non-int of type 'list'

In [19]:
array1 = np.array([1,2,3])
array3 = np.array([4,5,6])

In [22]:
array1*array3

array([ 4, 10, 18])

In [23]:
# 차원 알아보기

array1.shape

(3,)

In [26]:
array2.shape

(2, 3)

In [27]:
ndarray = np.array([[[1,2,3.5], 
                     [4,5,6]], 
                    [[7,8,9], 
                     [10,11,12]]])

In [28]:
ndarray.shape

(2, 2, 3)

In [29]:
ndarray

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [30]:
ndarray.astype('float')

array([[[ 1.,  2.,  3.],
        [ 4.,  5.,  6.]],

       [[ 7.,  8.,  9.],
        [10., 11., 12.]]])

numpy.zeros(shape, dtype=float, order='C', *, like=None)

In [32]:
# zeros() 메소드

np.zeros(10) + 10

array([10., 10., 10., 10., 10., 10., 10., 10., 10., 10.])

In [35]:
np.ones(10)*2

array([2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])

In [36]:
np.two(10) # 비트는 0과 1로 / 바로 위 참조

AttributeError: module 'numpy' has no attribute 'two'

In [37]:
np.ones((2, 5, 3), dtype=int)*2

array([[[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]],

       [[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]]])

In [38]:
ndarray = np.ones((2, 5), dtype=int)*2

In [40]:
ndarray.shape

(2, 5)

##### sqrt


##### transpose()
numpy.transpose(a, axes=None)

In [3]:
x = np.arange(4).reshape((2,2))
np.nonetranspose(x)

AttributeError: module 'numpy' has no attribute 'nonetranspose'

In [1]:
# 교제 20p~21p 정리

In [2]:
a = np.array([10, 20, 30, 40, 50, 60, 70])
b = np.array(a[1:6:2])
print('b:', b)
b[1] = 10
print('b:', b)
print('a:', a)
type(b)

b: [20 40 60]
b: [20 10 60]
a: [10 20 30 40 50 60 70]


numpy.ndarray

##### np.random
random.random(size=None)

In [3]:
a = np.array([10,20,30,40,50,60,70])
b = a > 50
print(b)

[False False False False False  True  True]


In [5]:
array_rdm = np.random.random(5)
print(array_rdm)
print(type(array_rdm))
print(np.all(array_rdm >= 0))
print(np.any(array_rdm > 0.7))

[0.18710474 0.66929237 0.05738173 0.6185754  0.19919337]
<class 'numpy.ndarray'>
True
False


##### linspace
numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)

In [6]:
# 0과 12 를 포함한 그 사이의 값들을 선형적으로 분배하여 모두 4개의 원소를 갖는 배열을 생성

In [9]:
np.llinspace(0, 12, 4)

AttributeError: module 'numpy' has no attribute 'llinspace'

np.linspace(0, 12, num=4)
np.linspace(0, 12, 4, retstep=True)
np.linspace(0, 12, 4, False)

In [11]:
print(arr_1, arr_2, arr_3)

NameError: name 'arr_1' is not defined

##### logsapce
numpy.logspace(start, stop, num=50, endpoint=True, base=10.0, dtype=None, axis=0)

In [18]:
np.logspace(np.log10(10), np.log10(100), 5)

array([ 10.        ,  17.7827941 ,  31.6227766 ,  56.23413252,
       100.        ])

In [19]:
np.logspace(1, 2, 5)

array([ 10.        ,  17.7827941 ,  31.6227766 ,  56.23413252,
       100.        ])

##### random.rand()
random.rand(d0, d1, ..., dn)

In [26]:
#np.random.seed(10)
np.random.rand(5)
# np.random.rand(2,3)

array([0.97862378, 0.81168315, 0.17194101, 0.81622475, 0.27407375])

In [27]:
np.random.seed(10)
np.random.rand(5)
# np.random.rand(2,3)

array([0.77132064, 0.02075195, 0.63364823, 0.74880388, 0.49850701])

In [28]:
np.random.rand(2,3)

array([[0.22479665, 0.19806286, 0.76053071],
       [0.16911084, 0.08833981, 0.68535982]])

In [29]:
np.random.rand(10, 5)

array([[0.95339335, 0.00394827, 0.51219226, 0.81262096, 0.61252607],
       [0.72175532, 0.29187607, 0.91777412, 0.71457578, 0.54254437],
       [0.14217005, 0.37334076, 0.67413362, 0.44183317, 0.43401399],
       [0.61776698, 0.51313824, 0.65039718, 0.60103895, 0.8052232 ],
       [0.52164715, 0.90864888, 0.31923609, 0.09045935, 0.30070006],
       [0.11398436, 0.82868133, 0.04689632, 0.62628715, 0.54758616],
       [0.819287  , 0.19894754, 0.8568503 , 0.35165264, 0.75464769],
       [0.29596171, 0.88393648, 0.32551164, 0.1650159 , 0.39252924],
       [0.09346037, 0.82110566, 0.15115202, 0.38411445, 0.94426071],
       [0.98762547, 0.45630455, 0.82612284, 0.25137413, 0.59737165]])

##### numpy.random.randn
random.randn(d0, d1, ..., dn)
Return a sample (or samples) from the “standard normal” distribution.

In [31]:
np.random.randn(5)

array([ 0.07878845,  0.91841365, -0.49269736,  0.09646237, -0.65275994])

In [32]:
np.random.randn(5, 4)

array([[-0.22176244, -1.06828657, -1.22769205, -1.79857302],
       [-0.68520734, -1.40986887,  1.25239859,  0.46956276],
       [ 0.32692165,  1.80854321, -1.413068  ,  2.52330509],
       [ 0.3473178 , -0.88735951, -1.05961725,  0.34795146],
       [-1.55866445, -0.99504103,  2.62115252, -0.34088642]])

In [33]:
m = 10; sigma = 2
m + sigma*np.random.randn(5)

array([ 9.67581169, 10.86591902,  9.99101308,  6.27055723,  8.78454828])